import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}
  public all_books = [
    {
      id: 1,
      bookImg: '/assets/img/1.jpg',
      bookName: 'EMILE ZOLA',
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 2,
      bookImg: '/assets/img/2.jpg',
      bookName: 'FATHERHOOD',
      authName: 'Marcus Berkmann',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 3,
      bookImg: '/assets/img/3.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 4,
      bookImg: '/assets/img/4.jpg',
      bookName: 'EMILE ZOLA',
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 5,
      bookImg: '/assets/img/5.jpg',
      bookName: 'FATHERHOOD',
      authName: 'Marcus Berkmann',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 6,
      bookImg: '/assets/img/6.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 7,
      bookImg: '/assets/img/7.jpg',
      bookName: 'EMILE ZOLA',
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 8,
      bookImg: '/assets/img/10.jpg',
      bookName: 'FATHERHOOD',
      authName: 'Marcus Berkmann',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 9,
      bookImg: '/assets/img/11.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 10,
      bookImg: '/assets/img/12.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
  ];

  public Famous_books = [
    {
      id: 1,
      bookImg: '/assets/img/b1.jpg',
      bookName: 'EMILE ZOLA',
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 2,
      bookImg: '/assets/img/b2.jpg',
      bookName: 'FATHERHOOD',
      authName: 'Marcus Berkmann',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 3,
      bookImg: '/assets/img/b3.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 4,
      bookImg: '/assets/img/b4.jpg',
      bookName: 'EMILE ZOLA',
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 5,
      bookImg: '/assets/img/b5.jpg',
      bookName: 'FATHERHOOD',
      authName: 'Marcus Berkmann',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 6,
      bookImg: '/assets/img/b6.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 7,
      bookImg: '/assets/img/h1.jpg',
      bookName: 'EMILE ZOLA',
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
      ],
    },
    {
      id: 8,
      bookImg: '/assets/img/h2.jpg',
      bookName: 'FATHERHOOD',
      authName: 'Marcus Berkmann',
    },
    {
      id: 9,
      bookImg: '/assets/img/h3.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
    },
    {
      id: 10,
      bookImg: '/assets/img/12.jpg',
      bookName: "TRAVELLER'S",
      authName: 'Michael Rosen',
      bookImages: [
        '/assets/img/ob1.png',
        '/assets/img/ob2.png',
        '/assets/img/ob3.png',
        '/assets/img/ob1.png',
      ],
    },
  ];
}
